const $=id=>document.getElementById(id);
let state=null, dragging=false, inputUntil=0, powerTimer, seaTimer, messageTimer;
function message(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);clearTimeout(messageTimer);if(!error)messageTimer=setTimeout(()=>{$('message').textContent='Propulsion works with the dock deployed. Lower the platform before closing the lids.'},5000)}
async function command(name,args={}){try{const r=await fetch('/api/command/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(args)});const result=await r.json();if(!r.ok)throw new Error(typeof result.detail==='string'?result.detail:JSON.stringify(result.detail));return result}catch(e){message(e.message,true);return null}}
document.querySelectorAll('[data-command]').forEach(button=>button.onclick=async()=>{if(await command(button.dataset.command))message(button.textContent+' requested. Watch the position indicator.');});
$('stop-motors').onclick=async()=>{await command('stop_motor');$('port').value=$('starboard').value=0;$('port-output').textContent=$('starboard-output').textContent='0%';message('Both motor power commands set to zero. The boat will coast.')};
$('emergency').onclick=async()=>{await command('emergency_stop');message('Emergency stop latched. Motor power is zero and the mechanisms hold position.',true)};
$('reset-emergency').onclick=async()=>{if(await command('reset_emergency_stop'))message('Emergency stop reset.')};
$('reset-sim').onclick=async()=>{if(await command('reset'))message('Simulation reset to floating equilibrium.')};
$('pause').onclick=async()=>{await command('pause',{paused:!state?.paused})};
for(const id of ['port','starboard']){$(id).addEventListener('input',()=>{inputUntil=Date.now()+600;$(id+'-output').textContent=$(id).value+'%';clearTimeout(powerTimer);powerTimer=setTimeout(()=>command('set_motor_power',{port:+$('port').value,starboard:+$('starboard').value}),150)});$(id).addEventListener('change',()=>{clearTimeout(powerTimer);command('set_motor_power',{port:+$('port').value,starboard:+$('starboard').value})});}
function sea(){clearTimeout(seaTimer);seaTimer=setTimeout(()=>command('set_environment',{wave_height:+$('wave-height').value/100,wave_period:+$('period').value,wave_direction:+$('direction').value,current_x:+$('current-x').value,current_y:+$('current-y').value}),150)}
for(const id of ['wave-height','period','direction','current-x','current-y'])$(id).addEventListener('input',()=>{$('wave-output').textContent=$('wave-height').value+' cm';sea()});
$('preset').onchange=()=>{const preset={calm:[0,3],harbor:[6,3],swell:[18,4.5]}[$('preset').value];$('wave-height').value=preset[0];$('period').value=preset[1];$('wave-output').textContent=preset[0]+' cm';sea()};
for(const id of ['internals','underwater','references'])$(id).onchange=()=>command('view',{[id]:$(id).checked});
$('fps').onchange=()=>command('quality',{fps:+$('fps').value});$('camera-fps').onchange=()=>command('quality',{camera_fps:+$('camera-fps').value});$('animated-water').onchange=()=>command('quality',{water:$('animated-water').checked});
let view={azimuth:140,elevation:-24,distance:4.1},pointer=null,lastView=0;
function updateView(force=false){if(force||Date.now()-lastView>100){lastView=Date.now();command('view',view)}}
$('reset-view').onclick=()=>{view={azimuth:140,elevation:-24,distance:4.1};updateView(true)};
$('overview').onpointerdown=e=>{pointer=[e.clientX,e.clientY];dragging=true;e.target.setPointerCapture(e.pointerId)};
$('overview').onpointermove=e=>{if(!pointer)return;view.azimuth-=(e.clientX-pointer[0])*.35;view.elevation=Math.max(-85,Math.min(-5,view.elevation+(e.clientY-pointer[1])*.25));pointer=[e.clientX,e.clientY];updateView()};
$('overview').onpointerup=()=>{pointer=null;dragging=false;updateView(true)};
$('overview').addEventListener('wheel',e=>{e.preventDefault();view.distance=Math.max(1.8,Math.min(180,view.distance*Math.exp(e.deltaY*.001)));updateView()},{passive:false});
async function poll(){try{const r=await fetch('/api/status',{cache:'no-store'});state=await r.json();if(!state.ready){$('connection').textContent=state.error?'Simulator stopped':'Loading simulator';if(state.error)message(state.error,true);return}$('loading').classList.add('hidden');$('connection').textContent=state.emergency?'Emergency stop latched':state.paused?'Simulation paused':'Simulator connected';$('connection-dot').className=state.emergency?'offline':'online';$('speed').textContent=state.speed_kmh.toFixed(2);$('heading').textContent=(((state.heading_deg%360)+360)%360).toFixed(0)+'°';$('roll').textContent=state.roll_deg.toFixed(1)+'°';$('pitch').textContent=state.pitch_deg.toFixed(1)+'°';$('sim-time').textContent=state.time.toFixed(1)+' s';$('pause').textContent=state.paused?'Resume':'Pause';$('port-rpm').textContent=state.rpm[0].toFixed(0)+' rpm';$('starboard-rpm').textContent=state.rpm[1].toFixed(0)+' rpm';if(Date.now()>inputUntil){for(const id of ['port','starboard']){$(id).value=state[id+'_power'];$(id+'-output').textContent=state[id+'_power'].toFixed(0)+'%'}}const lid=(state.aft_lid+state.fore_lid)/2;$('lid-progress').value=lid;$('platform-progress').value=state.platform;$('lid-position').textContent=lid<.02?'Closed':lid>.98?'Open':Math.round(lid*100)+'% open';$('platform-position').textContent=state.platform<.02?'Lowered':state.platform>.98?'Raised':Math.round(state.platform*100)+'% raised';$('mechanism-state').textContent=state.emergency?'Stopped':state.busy?'Moving':state.platform>.98?'Ready for landing':'Ready';const blocked=state.emergency||state.busy;$('open-lid').disabled=blocked||lid>.98;$('close-lid').disabled=blocked||state.platform>.02||lid<.02;$('raise-platform').disabled=blocked||Math.min(state.aft_lid,state.fore_lid)<.98||state.platform>.98;$('lower-platform').disabled=blocked||state.platform<.02;const canDrive=!state.emergency;$('port').disabled=$('starboard').disabled=!canDrive;$('reset-emergency').disabled=!state.emergency;$('part-count').textContent=state.cad_parts+' / '+state.cad_parts+' CAD parts exported';const p=state.performance;$('performance').textContent=p?.real_time_factor!==undefined?'Physics '+p.physics_ms_per_step+' ms/step · '+p.real_time_factor+'× real time':'Physics running';if(state.render_error)message('Camera rendering failed: '+state.render_error,true)}catch(e){$('connection').textContent='Connection lost';$('connection-dot').className='offline';message('Connection lost. Check that the simulator launch window is still running.',true)}}
poll();setInterval(poll,400);
$('test-drain').onclick=()=>command('add_cabin_water',{litres:+$('test-water').value});
$('rain').onchange=()=>command('set_drainage',{rain_mm_h:+$('rain').value});
setInterval(()=>{if(!state?.ready)return;$('cabin-water').textContent=(state.cabin_water_l||0).toFixed(2)+' L';$('drain-pumps').textContent=(state.drain_primary?'On':'Off')+' / '+(state.drain_backup?'On':'Off');$('drain-flow').textContent=(state.drain_flow_lpm||[0,0]).reduce((a,b)=>a+b,0).toFixed(1)+' L/min';$('drain-pickup').textContent=state.drain_pickup===null?'None':['Aft port','Fore port','Aft starboard','Fore starboard'][state.drain_pickup];$('drain-state').textContent=state.drain_high_water?'High water':state.drain_primary||state.drain_backup?'Pumping':'Automatic';$('drain-state').classList.toggle('drain-alarm',!!state.drain_high_water);},400);

let worldData=null,worldKey='',loadingWorld=false,worldBusy=false;
function optionalSeed(id){const value=$(id).value;return value===''?null:Number(value)}
async function generateWorld(pathOnly=false){if(worldBusy)return;worldBusy=true;$('new-world').disabled=$('new-path').disabled=true;try{const result=await command(pathOnly?'new_path':'new_world',pathOnly?{seed:optionalSeed('path-seed')}:{kind:$('world-kind').value,seed:optionalSeed('world-seed'),path_seed:optionalSeed('path-seed')});if(result){worldKey='';message(pathOnly?'New route generated. Automatic driving started.':'New world and route generated. Automatic driving started.')}}finally{worldBusy=false;$('new-world').disabled=$('new-path').disabled=false}}
$('new-world').onclick=()=>generateWorld(false);$('new-path').onclick=()=>generateWorld(true);
$('manual-control').onclick=async()=>{if(await command('manual_control'))message('Manual control. Use the two motor sliders; the boat will coast until powered.')};
$('follow-path').onclick=async()=>{if(await command('follow_path'))message('Automatic route following resumed.')};
$('show-route').onchange=()=>command('view',{route:$('show-route').checked});
$('wide-view').onclick=()=>{let azimuth=140;if(worldData?.coastline&&state?.position){const p=state.position,coast=worldData.coastline.reduce((a,b)=>Math.hypot(a[0]-p[0],a[1]-p[1])<Math.hypot(b[0]-p[0],b[1]-p[1])?a:b);azimuth=Math.atan2(p[1]-coast[1],p[0]-coast[0])*180/Math.PI+180}view={azimuth,elevation:-32,distance:65};updateView(true)};
function drawMap(){if(!worldData||!state?.position)return;const canvas=$('route-map'),c=canvas.getContext('2d'),coast=worldData.coastline,path=worldData.route.waypoints;const points=coast.concat(path.map(p=>[p.x,p.y]));points.push(state.position);const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);let minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);const scale=Math.min((canvas.width-40)/Math.max(1,maxX-minX),(canvas.height-40)/Math.max(1,maxY-minY));const dx=(canvas.width-scale*(maxX-minX))/2,dy=(canvas.height-scale*(maxY-minY))/2;const screen=p=>[dx+(p[0]-minX)*scale,canvas.height-dy-(p[1]-minY)*scale];c.fillStyle='#bed5de';c.fillRect(0,0,canvas.width,canvas.height);c.beginPath();coast.forEach((p,i)=>{const q=screen(p);i?c.lineTo(...q):c.moveTo(...q)});if(worldData.kind!=='island'){c.lineTo(...screen([coast.at(-1)[0],maxY+1000]));c.lineTo(...screen([coast[0][0],maxY+1000]))}c.closePath();c.fillStyle=worldData.kind==='city'?'#9caaa5':worldData.kind==='rock'?'#9e9d8d':'#86a778';c.fill();c.beginPath();coast.forEach((p,i)=>{const q=screen(p);i?c.lineTo(...q):c.moveTo(...q)});c.strokeStyle=worldData.kind==='city'?'#687c80':'#dcc9a1';c.lineWidth=6;c.stroke();c.beginPath();path.forEach((p,i)=>{const q=screen([p.x,p.y]);i?c.lineTo(...q):c.moveTo(...q)});c.strokeStyle='#006e74';c.lineWidth=2.5;c.stroke();const p=screen(state.position);c.save();c.translate(...p);c.rotate(-state.heading_deg*Math.PI/180);c.beginPath();c.moveTo(9,0);c.lineTo(-7,-5);c.lineTo(-5,0);c.lineTo(-7,5);c.closePath();c.fillStyle='#153444';c.fill();c.restore();c.fillStyle='#234958';c.font='18px Segoe UI';c.fillText('N ↑',canvas.width-52,25);c.font='15px Segoe UI';c.fillText('Coastline + planned route',15,canvas.height-12)}
setInterval(async()=>{if(!state?.ready||!state.world)return;const w=state.world,key=w.seed+':'+w.path_seed+':'+w.kind;if(key!==worldKey&&!loadingWorld){loadingWorld=true;try{const r=await fetch('/api/world');if(!r.ok)throw Error('World export failed');worldData=await r.json();worldKey=worldData.world_seed+':'+worldData.route.path_seed+':'+worldData.kind}catch(e){message(e.message,true)}finally{loadingWorld=false}}$('control-mode').textContent=state.control_mode==='automatic'?'Automatic':state.control_mode==='finished'?'Complete':'Manual';$('control-mode').dataset.mode=state.control_mode;$('world-name').textContent=w.name;$('world-length').textContent=(w.coastline_length_m/1000).toFixed(2)+' km coast';$('active-seeds').textContent=w.seed+' / '+w.path_seed;$('route-segment').textContent=state.route_segment;$('coast-distance').textContent=state.coast_distance_m.toFixed(1)+' m';$('target-speed').textContent=(state.route_target_speed_mps*3.6).toFixed(1)+' km/h';$('route-distance').textContent=(state.route_progress_m/1000).toFixed(2)+' / '+(w.route_length_m/1000).toFixed(2)+' km';$('route-progress').value=state.route_progress;$('follow-path').disabled=state.emergency||state.control_mode==='automatic'||state.route_complete;$('manual-control').disabled=state.control_mode==='manual';const s=state.scenery;if(s)$('chunk-info').textContent=s.visible_chunks+' nearby chunks · '+s.scenery_geoms+' scenery shapes · '+s.render_radius_m+' m radius';drawMap()},400);
